version: "3.5"

services:
  mysql:
    container_name: rt-mysql
    image: mysql:5.7
    command: --max_allowed_packet=1024M
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - 3306:3306
    networks:
      - rt-network
    volumes:
      - mysql-rt-volume:/var/lib/mysql
  rt:
    container_name: rt
    image: patye/rt:1
    environment:
      - RT_WEB_PORT=8080
    ports:
      - 8080:80
    networks:
      - rt-network
    volumes:
      - $PWD/Custom_SiteConfig.pm:/opt/rt4/etc/RT_SiteConfig.d/Custom_SiteConfig.pm
      - $PWD/plugins:/opt/rt4/local/plugins
networks:
  rt-network:
volumes:
  mysql-rt-volume:
